// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:149

#ifndef _TAO_IDL_CIAO_EXCEPTIONSC_5JNILF_H_
#define _TAO_IDL_CIAO_EXCEPTIONSC_5JNILF_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "CIAO_Base_stub_export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/UserException.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 3 || TAO_BETA_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO CIAO_BASE_STUB_Export

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:35

namespace CIAO
{

  // TAO_IDL - Generated from
  // be\be_visitor_exception\exception_ch.cpp:41

  class CIAO_BASE_STUB_Export Installation_Failure : public ::CORBA::UserException
  {
  public:
    ::TAO::String_Manager name;
    ::TAO::String_Manager reason;

    Installation_Failure (void);
    Installation_Failure (const Installation_Failure &);
    ~Installation_Failure (void);

    Installation_Failure &operator= (const Installation_Failure &);

    static void _tao_any_destructor (void *);

    static Installation_Failure *_downcast ( ::CORBA::Exception *);
    static const Installation_Failure *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);

    // TAO_IDL - Generated from
    // be\be_visitor_exception\exception_ctor.cpp:51

    Installation_Failure (
        const char * _tao_name,
        const char * _tao_reason);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CIAO_BASE_STUB_Export ::CORBA::TypeCode_ptr const _tc_Installation_Failure;

  // TAO_IDL - Generated from
  // be\be_visitor_exception\exception_ch.cpp:41

  class CIAO_BASE_STUB_Export InvalidComponent : public ::CORBA::UserException
  {
  public:
    ::TAO::String_Manager name;
    ::TAO::String_Manager reason;

    InvalidComponent (void);
    InvalidComponent (const InvalidComponent &);
    ~InvalidComponent (void);

    InvalidComponent &operator= (const InvalidComponent &);

    static void _tao_any_destructor (void *);

    static InvalidComponent *_downcast ( ::CORBA::Exception *);
    static const InvalidComponent *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);

    // TAO_IDL - Generated from
    // be\be_visitor_exception\exception_ctor.cpp:51

    InvalidComponent (
        const char * _tao_name,
        const char * _tao_reason);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CIAO_BASE_STUB_Export ::CORBA::TypeCode_ptr const _tc_InvalidComponent;

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:64

} // module CIAO

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_exception\any_op_ch.cpp:38

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace CIAO
{
  

  CIAO_BASE_STUB_Export void operator<<= (::CORBA::Any &, const ::CIAO::Installation_Failure &); // copying version
  CIAO_BASE_STUB_Export void operator<<= (::CORBA::Any &, ::CIAO::Installation_Failure*); // noncopying version
  CIAO_BASE_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::CIAO::Installation_Failure *&); // deprecated
CIAO_BASE_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::CIAO::Installation_Failure *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CIAO_BASE_STUB_Export void operator<<= (::CORBA::Any &, const CIAO::Installation_Failure &); // copying version
CIAO_BASE_STUB_Export void operator<<= (::CORBA::Any &, CIAO::Installation_Failure*); // noncopying version
CIAO_BASE_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CIAO::Installation_Failure *&); // deprecated
CIAO_BASE_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CIAO::Installation_Failure *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_exception\any_op_ch.cpp:38

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace CIAO
{
  

  CIAO_BASE_STUB_Export void operator<<= (::CORBA::Any &, const ::CIAO::InvalidComponent &); // copying version
  CIAO_BASE_STUB_Export void operator<<= (::CORBA::Any &, ::CIAO::InvalidComponent*); // noncopying version
  CIAO_BASE_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::CIAO::InvalidComponent *&); // deprecated
CIAO_BASE_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::CIAO::InvalidComponent *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CIAO_BASE_STUB_Export void operator<<= (::CORBA::Any &, const CIAO::InvalidComponent &); // copying version
CIAO_BASE_STUB_Export void operator<<= (::CORBA::Any &, CIAO::InvalidComponent*); // noncopying version
CIAO_BASE_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CIAO::InvalidComponent *&); // deprecated
CIAO_BASE_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CIAO::InvalidComponent *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_exception\cdr_op_ch.cpp:37
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CIAO_BASE_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const CIAO::Installation_Failure &);
CIAO_BASE_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, CIAO::Installation_Failure &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_exception\cdr_op_ch.cpp:37
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CIAO_BASE_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const CIAO::InvalidComponent &);
CIAO_BASE_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, CIAO::InvalidComponent &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_codegen.cpp:1700
#include /**/ "ace/post.h"

#endif /* ifndef */

