// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:149

#ifndef _TAO_IDL_CIAO_PROPERTIESC_GXFLOH_H_
#define _TAO_IDL_CIAO_PROPERTIESC_GXFLOH_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "CIAO_Base_stub_export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 3 || TAO_BETA_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO CIAO_BASE_STUB_Export

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:35

namespace CIAO
{

  // TAO_IDL - Generated from
  // be\be_visitor_module\module_ch.cpp:35

  namespace Deployment
  {

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const SVNT_ENTRYPT = "edu.vanderbilt.dre.CIAO.ServantEntrypoint";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const SVNT_ARTIFACT = "edu.vanderbilt.dre.CIAO.ServantArtifact";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const EXEC_ARTIFACT = "edu.vanderbilt.dre.CIAO.ExecutorArtifact";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const OPEN_MODE = "edu.vanderbilt.dre.CIAO.OpenMode";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const COMPONENT_FACTORY = "component factory";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const HOME_FACTORY = "home factory";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const COMPONENT_HOME = "edu.vanderbilt.dre.CIAO.ComponentHomeId";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const CONTAINER_ID = "edu.vanderbilt.dre.CIAO.ContainerId";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const CCM_CONTAINER = "edu.vanderbilt.dre.CCM.Container";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const CCM_HOME = "edu.vanderbilt.dre.CCM.Home";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const CCM_COMPONENT = "edu.vanderbilt.dre.CCM.Component";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const CCM_HOMEDCOMPONENT = "edu.vanderbilt.dre.CCM.HomedComponent";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const CCM_CONNECTOR = "edu.vanderbilt.dre.CCM.Connector";

    // TAO_IDL - Generated from
    // be\be_visitor_constant\constant_ch.cpp:35

    const char *const SERVICE_REF = "edu.vanderbilt.dre.CIAO.ServiceReference";
  
  // TAO_IDL - Generated from
  // be\be_visitor_module\module_ch.cpp:64
  
  } // module CIAO::Deployment

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:64

} // module CIAO

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_codegen.cpp:1700
#include /**/ "ace/post.h"

#endif /* ifndef */

