// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:1172

#ifndef CIAO_SERVANT_AMI4CCM_SVNT_T_H5FGMA_H_
#define CIAO_SERVANT_AMI4CCM_SVNT_T_H5FGMA_H_

#include /**/ "ace/pre.h"

#include /**/ "ami4ccm_svnt_export.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "ciao/Servants/Session/Servant_Impl_T.h"
#include "ciao/Servants/Home_Servant_Impl_T.h"
#include "ciao/Servants/Facet_Servant_Base_T.h"

#include "ami4ccmEC.h"

#include "ami4ccmS.h"
#include "connectors/ami4ccm/ami4ccm/ami4ccm_svnt.h"


namespace CIAO_CCM_AMI_AMI4CCM_Base_Impl
{
  class AMI4CCM_Base_Servant;

  template <typename CONTAINER_TYPE, typename BASE>
  class AMI4CCM_Base_Context_T
    : public BASE
  {
  public:
    /// Allow the servant to access our state.
    friend class AMI4CCM_Base_Servant;

    typedef ::CIAO::Connector_Servant_Impl_Base svnt_base_type;

    AMI4CCM_Base_Context_T (
      ::Components::CCMHome_ptr h,
      typename CONTAINER_TYPE::_ptr_type c,
      PortableServer::Servant sv,
      const char *id);

    virtual ~AMI4CCM_Base_Context_T (void);

    /** @name Operations and members for AMI4CCM_Base receptacles and event sources,
     * defined in ::CCM_AMI::CCM_AMI4CCM_Base_Context.
     */
    //@{
    //@}
  };
}

#if defined (ACE_TEMPLATES_REQUIRE_SOURCE)
#include "ami4ccm_svnt_T.cpp"
#endif /* ACE_TEMPLATES_REQUIRE_SOURCE */

#if defined (ACE_TEMPLATES_REQUIRE_PRAGMA)
#pragma implementation ("ami4ccm_svnt_T.cpp")
#endif /* ACE_TEMPLATES_REQUIRE_PRAGMA */


#include /**/ "ace/post.h"

#endif /* ifndef */
