// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:149

#ifndef _TAO_IDL_CCM_COOKIEC_TGVGFA_H_
#define _TAO_IDL_CCM_COOKIEC_TGVGFA_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "CCM_Stub_Export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/Valuetype/ValueBase.h"
#include "tao/Valuetype/Valuetype_Adapter_Factory_Impl.h"
#include "tao/Valuetype/ValueFactory.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/AnyTypeCode/OctetSeqA.h"
#include "tao/Valuetype/Value_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "tao/OctetSeqC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 3 || TAO_BETA_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO CCM_STUB_Export

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:35

namespace Components
{

  // TAO_IDL - Generated from
  // be\be_valuetype.cpp:564

  

#if !defined (_COMPONENTS_COOKIE__VAR_OUT_CH_)
#define _COMPONENTS_COOKIE__VAR_OUT_CH_

  class Cookie;
  typedef
    TAO_Value_Var_T<
        Cookie
      >
    Cookie_var;
  
  typedef
    TAO_Value_Out_T<
        Cookie
      >
    Cookie_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be\be_visitor_valuetype\valuetype_ch.cpp:50

  class CCM_STUB_Export Cookie
    : public virtual ::CORBA::ValueBase
  {
  public:

    // TAO_IDL - Generated from
    // be\be_type.cpp:304

    typedef Cookie * _ptr_type;
    typedef Cookie_var _var_type;
    typedef Cookie_out _out_type;

    static void _tao_any_destructor (void *);

    static Cookie* _downcast ( ::CORBA::ValueBase *v);
    
    /// TAO extensions or internals
    static ::CORBA::Boolean _tao_unmarshal (
        TAO_InputCDR &strm,
        Cookie *&new_object);
    
    virtual const char* _tao_obv_repository_id (void) const;

    virtual void _tao_obv_truncatable_repo_ids (Repository_Id_List &) const;

    static const char* _tao_obv_static_repository_id (void);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  
  protected:

    // TAO_IDL - Generated from
    // be\be_visitor_valuetype\field_ch.cpp:533

    virtual void cookieValue (const CORBA::OctetSeq &) = 0;
    virtual const CORBA::OctetSeq &cookieValue (void) const = 0;
    virtual CORBA::OctetSeq &cookieValue (void) = 0;

    // TAO_IDL - Generated from
    // be\be_visitor_valuetype\valuetype_ch.cpp:238
  
  protected:
    Cookie (void);
    virtual ~Cookie (void);

    virtual ::CORBA::Boolean _tao_marshal_v (TAO_OutputCDR &) const;
    virtual ::CORBA::Boolean _tao_unmarshal_v (TAO_InputCDR &);
    virtual ::CORBA::Boolean _tao_match_formal_type (ptrdiff_t ) const;
    
  private:
    Cookie (const Cookie &);
    void operator= (const Cookie &);
    
  protected:
    virtual ::CORBA::Boolean
    _tao_marshal__Components_Cookie (TAO_OutputCDR &, TAO_ChunkInfo &) const = 0;

    virtual ::CORBA::Boolean
    _tao_unmarshal__Components_Cookie (TAO_InputCDR &, TAO_ChunkInfo &) = 0;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_valuetype\valuetype_init_ch.cpp:57

  class CCM_STUB_Export Cookie_init
    : public virtual ::CORBA::ValueFactoryBase
  {
  public:
    Cookie_init (void);

    static Cookie_init* _downcast ( ::CORBA::ValueFactoryBase *);

    virtual ::CORBA::ValueBase *
    create_for_unmarshal (void);

    // TAO-specific extensions
  public:
    virtual const char* tao_repository_id (void);
  
  protected:
    virtual ~Cookie_init (void);
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_Cookie;

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:64

} // module Components

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:306

#if !defined (_COMPONENTS_COOKIE__ARG_TRAITS_)
#define _COMPONENTS_COOKIE__ARG_TRAITS_

  template<>
  class Arg_Traits< ::Components::Cookie>
    : public
        Object_Arg_Traits_T<
            ::Components::Cookie *,
            ::Components::Cookie_var,
            ::Components::Cookie_out,
            TAO::Value_Traits<Components::Cookie>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_valuetype\obv_module.cpp:44

namespace OBV_Components
{

  // TAO_IDL - Generated from
  // be\be_visitor_valuetype\valuetype_obv_ch.cpp:44

  // OBV_ class
  class CCM_STUB_Export Cookie
    : public virtual Components::Cookie,
      public virtual ::CORBA::DefaultValueRefCountBase
  {

protected:

  // TAO_IDL - Generated from
  // be\be_visitor_valuetype\field_ch.cpp:533

  virtual void cookieValue (const CORBA::OctetSeq &);
  virtual const CORBA::OctetSeq &cookieValue (void) const;
  virtual CORBA::OctetSeq &cookieValue (void);

public:
  Cookie (void);
  Cookie (
      const ::CORBA::OctetSeq & _tao_init_cookieValue
    );
  virtual ~Cookie (void);

public:
  virtual ::CORBA::ValueBase *_copy_value (void);
  
protected:
  virtual ::CORBA::Boolean
  _tao_marshal__Components_Cookie (TAO_OutputCDR &, TAO_ChunkInfo &) const;

  virtual ::CORBA::Boolean
  _tao_unmarshal__Components_Cookie (TAO_InputCDR &, TAO_ChunkInfo &);

  ::CORBA::Boolean _tao_marshal_state (TAO_OutputCDR &, TAO_ChunkInfo &) const;
  ::CORBA::Boolean _tao_unmarshal_state (TAO_InputCDR &, TAO_ChunkInfo &);
  virtual void truncation_hook (void);

private:
  CORBA::OctetSeq _pd_cookieValue;
  CORBA::Boolean require_truncation_;
};
}

// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_COMPONENTS_COOKIE__TRAITS_)
#define _COMPONENTS_COOKIE__TRAITS_

  template<>
  struct CCM_STUB_Export Value_Traits<Components::Cookie>
  {
    static void add_ref (Components::Cookie *);
    static void remove_ref (Components::Cookie *);
    static void release (Components::Cookie *);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_valuetype\any_op_ch.cpp:43



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, Cookie *); // copying
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, Cookie **); // non-copying
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Cookie *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::Cookie *); // copying
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::Cookie **); // non-copying
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::Cookie *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_valuetype.cpp:456


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  extern CCM_STUB_Export void add_ref (Components::Cookie *);
  extern CCM_STUB_Export void remove_ref (Components::Cookie *);
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_valuetype\cdr_op_ch.cpp:49


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::Cookie *);
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::Cookie *&);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_codegen.cpp:1700
#if defined (__ACE_INLINE__)
#include "CCM_CookieC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

