// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:149

#ifndef _TAO_IDL_CCM_NAVIGATIONC_YQDHFW_H_
#define _TAO_IDL_CCM_NAVIGATIONC_YQDHFW_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "CCM_Stub_Export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/UserException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/AnyTypeCode/orb_typesA.h"
#include "tao/AnyTypeCode/StringSeqA.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "tao/orb_typesC.h"
#include "tao/StringSeqC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 3 || TAO_BETA_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO CCM_STUB_Export

// TAO_IDL - Generated from
// be\be_visitor_root\root_ch.cpp:157
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:35

namespace Components
{

  // TAO_IDL - Generated from
  // be\be_visitor_typedef\typedef_ch.cpp:404

  typedef char * FeatureName;
  typedef ::CORBA::String_var FeatureName_var;
  typedef ::CORBA::String_out FeatureName_out;

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_FeatureName;

  // TAO_IDL - Generated from
  // be\be_visitor_sequence\sequence_ch.cpp:99

#if !defined (_COMPONENTS_NAMELIST_CH_)
#define _COMPONENTS_NAMELIST_CH_

  class NameList;

  typedef
    ::TAO_VarSeq_Var_T<
        NameList
      >
    NameList_var;

  typedef
    ::TAO_Seq_Out_T<
        NameList
      >
    NameList_out;

  class CCM_STUB_Export NameList
    : public
        ::TAO::unbounded_basic_string_sequence<char>
  {
  public:
    NameList (void);
    NameList ( ::CORBA::ULong max);
    NameList (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Char ** buffer,
      ::CORBA::Boolean release = false);
    NameList (const NameList &);
    virtual ~NameList (void);
    

    // TAO_IDL - Generated from
    // be\be_type.cpp:304

    
    typedef NameList_var _var_type;
    typedef NameList_out _out_type;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_NameList;

  // TAO_IDL - Generated from
  // be\be_visitor_exception\exception_ch.cpp:41

  class CCM_STUB_Export InvalidName : public ::CORBA::UserException
  {
  public:

    InvalidName (void);
    InvalidName (const InvalidName &);
    ~InvalidName (void);

    InvalidName &operator= (const InvalidName &);

    static void _tao_any_destructor (void *);

    static InvalidName *_downcast ( ::CORBA::Exception *);
    static const InvalidName *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_InvalidName;

  // TAO_IDL - Generated from
  // be\be_interface.cpp:748

#if !defined (_COMPONENTS_NAVIGATION__VAR_OUT_CH_)
#define _COMPONENTS_NAVIGATION__VAR_OUT_CH_

  class Navigation;
  typedef Navigation *Navigation_ptr;

  typedef
    TAO_Objref_Var_T<
        Navigation
      >
    Navigation_var;
  
  typedef
    TAO_Objref_Out_T<
        Navigation
      >
    Navigation_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be\be_visitor_interface\interface_ch.cpp:40

  class CCM_STUB_Export Navigation
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<Navigation>;

    // TAO_IDL - Generated from
    // be\be_type.cpp:304

    typedef Navigation_ptr _ptr_type;
    typedef Navigation_var _var_type;
    typedef Navigation_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static Navigation_ptr _duplicate (Navigation_ptr obj);

    static void _tao_release (Navigation_ptr obj);

    static Navigation_ptr _narrow (::CORBA::Object_ptr obj);
    static Navigation_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static Navigation_ptr _nil (void);

    virtual ::CORBA::Object_ptr provide_facet (
      const char * name);

    // TAO_IDL - Generated from
    // be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    Navigation (void);

    // Concrete non-local interface only.
    Navigation (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    Navigation (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~Navigation (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    Navigation (const Navigation &);

    void operator= (const Navigation &);
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_Navigation;

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:64

} // module Components

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:683

  template<>
  class Arg_Traits< ::Components::NameList>
    : public
        Var_Size_Arg_Traits_T<
            ::Components::NameList,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:145

#if !defined (_COMPONENTS_NAVIGATION__ARG_TRAITS_)
#define _COMPONENTS_NAVIGATION__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::Components::Navigation>
    : public
        Object_Arg_Traits_T<
            ::Components::Navigation_ptr,
            ::Components::Navigation_var,
            ::Components::Navigation_out,
            TAO::Objref_Traits<Components::Navigation>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_COMPONENTS_NAVIGATION__TRAITS_)
#define _COMPONENTS_NAVIGATION__TRAITS_

  template<>
  struct CCM_STUB_Export Objref_Traits< ::Components::Navigation>
  {
    static ::Components::Navigation_ptr duplicate (
        ::Components::Navigation_ptr p);
    static void release (
        ::Components::Navigation_ptr p);
    static ::Components::Navigation_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Components::Navigation_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_sequence\any_op_ch.cpp:47



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, const ::Components::NameList &); // copying version
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, ::Components::NameList*); // noncopying version
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::Components::NameList *&); // deprecated
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::Components::NameList *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

CCM_STUB_Export void operator<<= ( ::CORBA::Any &, const Components::NameList &); // copying version
CCM_STUB_Export void operator<<= ( ::CORBA::Any &, Components::NameList*); // noncopying version
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::NameList *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const Components::NameList *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_exception\any_op_ch.cpp:38

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  

  CCM_STUB_Export void operator<<= (::CORBA::Any &, const ::Components::InvalidName &); // copying version
  CCM_STUB_Export void operator<<= (::CORBA::Any &, ::Components::InvalidName*); // noncopying version
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::Components::InvalidName *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::Components::InvalidName *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export void operator<<= (::CORBA::Any &, const Components::InvalidName &); // copying version
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::InvalidName*); // noncopying version
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::InvalidName *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const Components::InvalidName *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_interface\any_op_ch.cpp:41



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, Navigation_ptr); // copying
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, Navigation_ptr *); // non-copying
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Navigation_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::Navigation_ptr); // copying
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::Navigation_ptr *); // non-copying
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::Navigation_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_sequence\cdr_op_ch.cpp:65

#if !defined _TAO_CDR_OP_Components_NameList_H_
#define _TAO_CDR_OP_Components_NameList_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


CCM_STUB_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Components::NameList &_tao_sequence);
CCM_STUB_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Components::NameList &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Components_NameList_H_ */

// TAO_IDL - Generated from
// be\be_visitor_exception\cdr_op_ch.cpp:37
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::InvalidName &);
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::InvalidName &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_interface\cdr_op_ch.cpp:41

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::Navigation_ptr );
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::Navigation_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_codegen.cpp:1700
#if defined (__ACE_INLINE__)
#include "CCM_NavigationC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

