// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:458

#ifndef _TAO_IDL_CCM_KEYLESSCCMHOMES_G436OP_H_
#define _TAO_IDL_CCM_KEYLESSCCMHOMES_G436OP_H_

#include /**/ "ace/pre.h"

#include "CCM_KeylessCCMHomeC.h"
#include "ccm/CCM_ObjectS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

#include /**/ "CCM_Svnt_Export.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO CCM_SVNT_Export

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:145

#if !defined (_COMPONENTS_KEYLESSCCMHOME__SARG_TRAITS_)
#define _COMPONENTS_KEYLESSCCMHOME__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::Components::KeylessCCMHome>
    : public
        Object_SArg_Traits_T<
            ::Components::KeylessCCMHome_ptr,
            ::Components::KeylessCCMHome_var,
            ::Components::KeylessCCMHome_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_module\module_sh.cpp:35

namespace POA_Components
{
  

  // TAO_IDL - Generated from
  // be\be_visitor_interface\interface_sh.cpp:73

  class KeylessCCMHome;
  typedef KeylessCCMHome *KeylessCCMHome_ptr;

  class CCM_SVNT_Export KeylessCCMHome
    : public virtual PortableServer::ServantBase
  {
  protected:
    KeylessCCMHome (void);
  
  public:
    /// Useful for template programming.
    typedef ::Components::KeylessCCMHome _stub_type;
    typedef ::Components::KeylessCCMHome_ptr _stub_ptr_type;
    typedef ::Components::KeylessCCMHome_var _stub_var_type;

    KeylessCCMHome (const KeylessCCMHome& rhs);
    virtual ~KeylessCCMHome (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::Components::KeylessCCMHome *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // be\be_visitor_operation\operation_sh.cpp:36

    virtual ::Components::CCMObject_ptr create_component (
      void) = 0;

    static void create_component_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

// TAO_IDL - Generated from
// be\be_visitor_module\module_sh.cpp:66

} // module Components

#include /**/ "ace/post.h"

#endif /* ifndef */

