// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:149

#ifndef _TAO_IDL_CCM_EVENTCONSUMERBASEC_HK3XM2_H_
#define _TAO_IDL_CCM_EVENTCONSUMERBASEC_HK3XM2_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "CCM_Stub_Export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/UserException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/AnyTypeCode/orb_typesA.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "ccm/CCM_EventBaseC.h"
#include "tao/orb_typesC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 3 || TAO_BETA_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO CCM_STUB_Export

// TAO_IDL - Generated from
// be\be_visitor_root\root_ch.cpp:157
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:35

namespace Components
{

  // TAO_IDL - Generated from
  // be\be_visitor_exception\exception_ch.cpp:41

  class CCM_STUB_Export BadEventType : public ::CORBA::UserException
  {
  public:
    ::TAO::String_Manager expected_event_type;

    BadEventType (void);
    BadEventType (const BadEventType &);
    ~BadEventType (void);

    BadEventType &operator= (const BadEventType &);

    static void _tao_any_destructor (void *);

    static BadEventType *_downcast ( ::CORBA::Exception *);
    static const BadEventType *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);

    // TAO_IDL - Generated from
    // be\be_visitor_exception\exception_ctor.cpp:51

    BadEventType (
        const char * _tao_expected_event_type);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_BadEventType;

  // TAO_IDL - Generated from
  // be\be_interface.cpp:748

#if !defined (_COMPONENTS_EVENTCONSUMERBASE__VAR_OUT_CH_)
#define _COMPONENTS_EVENTCONSUMERBASE__VAR_OUT_CH_

  class EventConsumerBase;
  typedef EventConsumerBase *EventConsumerBase_ptr;

  typedef
    TAO_Objref_Var_T<
        EventConsumerBase
      >
    EventConsumerBase_var;
  
  typedef
    TAO_Objref_Out_T<
        EventConsumerBase
      >
    EventConsumerBase_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be\be_visitor_interface\interface_ch.cpp:40

  class CCM_STUB_Export EventConsumerBase
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<EventConsumerBase>;

    // TAO_IDL - Generated from
    // be\be_type.cpp:304

    typedef EventConsumerBase_ptr _ptr_type;
    typedef EventConsumerBase_var _var_type;
    typedef EventConsumerBase_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static EventConsumerBase_ptr _duplicate (EventConsumerBase_ptr obj);

    static void _tao_release (EventConsumerBase_ptr obj);

    static EventConsumerBase_ptr _narrow (::CORBA::Object_ptr obj);
    static EventConsumerBase_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static EventConsumerBase_ptr _nil (void);

    virtual void push_event (
      ::Components::EventBase * evt);

    // TAO_IDL - Generated from
    // be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    EventConsumerBase (void);

    // Concrete non-local interface only.
    EventConsumerBase (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    EventConsumerBase (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~EventConsumerBase (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    EventConsumerBase (const EventConsumerBase &);

    void operator= (const EventConsumerBase &);
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_EventConsumerBase;

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:64

} // module Components

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:145

#if !defined (_COMPONENTS_EVENTCONSUMERBASE__ARG_TRAITS_)
#define _COMPONENTS_EVENTCONSUMERBASE__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::Components::EventConsumerBase>
    : public
        Object_Arg_Traits_T<
            ::Components::EventConsumerBase_ptr,
            ::Components::EventConsumerBase_var,
            ::Components::EventConsumerBase_out,
            TAO::Objref_Traits<Components::EventConsumerBase>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_COMPONENTS_EVENTCONSUMERBASE__TRAITS_)
#define _COMPONENTS_EVENTCONSUMERBASE__TRAITS_

  template<>
  struct CCM_STUB_Export Objref_Traits< ::Components::EventConsumerBase>
  {
    static ::Components::EventConsumerBase_ptr duplicate (
        ::Components::EventConsumerBase_ptr p);
    static void release (
        ::Components::EventConsumerBase_ptr p);
    static ::Components::EventConsumerBase_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Components::EventConsumerBase_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_exception\any_op_ch.cpp:38

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  

  CCM_STUB_Export void operator<<= (::CORBA::Any &, const ::Components::BadEventType &); // copying version
  CCM_STUB_Export void operator<<= (::CORBA::Any &, ::Components::BadEventType*); // noncopying version
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::Components::BadEventType *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::Components::BadEventType *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export void operator<<= (::CORBA::Any &, const Components::BadEventType &); // copying version
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::BadEventType*); // noncopying version
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::BadEventType *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const Components::BadEventType *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_interface\any_op_ch.cpp:41



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, EventConsumerBase_ptr); // copying
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, EventConsumerBase_ptr *); // non-copying
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, EventConsumerBase_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::EventConsumerBase_ptr); // copying
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::EventConsumerBase_ptr *); // non-copying
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::EventConsumerBase_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_exception\cdr_op_ch.cpp:37
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::BadEventType &);
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::BadEventType &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_interface\cdr_op_ch.cpp:41

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::EventConsumerBase_ptr );
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::EventConsumerBase_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_codegen.cpp:1700
#if defined (__ACE_INLINE__)
#include "CCM_EventConsumerBaseC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

