// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:149

#ifndef _TAO_IDL_CCM_EXCEPTIONSC_BU30ZM_H_
#define _TAO_IDL_CCM_EXCEPTIONSC_BU30ZM_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "CCM_Stub_Export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/UserException.h"
#include "tao/Basic_Types.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 3 || TAO_BETA_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO CCM_STUB_Export

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:35

namespace Components
{

  // TAO_IDL - Generated from
  // be\be_visitor_typedef\typedef_ch.cpp:370

  typedef ::CORBA::ULong FailureReason;
  typedef ::CORBA::ULong_out FailureReason_out;

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_FailureReason;

  // TAO_IDL - Generated from
  // be\be_visitor_exception\exception_ch.cpp:41

  class CCM_STUB_Export CreateFailure : public ::CORBA::UserException
  {
  public:
    Components::FailureReason reason;

    CreateFailure (void);
    CreateFailure (const CreateFailure &);
    ~CreateFailure (void);

    CreateFailure &operator= (const CreateFailure &);

    static void _tao_any_destructor (void *);

    static CreateFailure *_downcast ( ::CORBA::Exception *);
    static const CreateFailure *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);

    // TAO_IDL - Generated from
    // be\be_visitor_exception\exception_ctor.cpp:51

    CreateFailure (
        Components::FailureReason _tao_reason);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_CreateFailure;

  // TAO_IDL - Generated from
  // be\be_visitor_exception\exception_ch.cpp:41

  class CCM_STUB_Export FinderFailure : public ::CORBA::UserException
  {
  public:
    Components::FailureReason reason;

    FinderFailure (void);
    FinderFailure (const FinderFailure &);
    ~FinderFailure (void);

    FinderFailure &operator= (const FinderFailure &);

    static void _tao_any_destructor (void *);

    static FinderFailure *_downcast ( ::CORBA::Exception *);
    static const FinderFailure *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);

    // TAO_IDL - Generated from
    // be\be_visitor_exception\exception_ctor.cpp:51

    FinderFailure (
        Components::FailureReason _tao_reason);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_FinderFailure;

  // TAO_IDL - Generated from
  // be\be_visitor_exception\exception_ch.cpp:41

  class CCM_STUB_Export RemoveFailure : public ::CORBA::UserException
  {
  public:
    Components::FailureReason reason;

    RemoveFailure (void);
    RemoveFailure (const RemoveFailure &);
    ~RemoveFailure (void);

    RemoveFailure &operator= (const RemoveFailure &);

    static void _tao_any_destructor (void *);

    static RemoveFailure *_downcast ( ::CORBA::Exception *);
    static const RemoveFailure *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);

    // TAO_IDL - Generated from
    // be\be_visitor_exception\exception_ctor.cpp:51

    RemoveFailure (
        Components::FailureReason _tao_reason);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_RemoveFailure;

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:64

} // module Components

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_exception\any_op_ch.cpp:38

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  

  CCM_STUB_Export void operator<<= (::CORBA::Any &, const ::Components::CreateFailure &); // copying version
  CCM_STUB_Export void operator<<= (::CORBA::Any &, ::Components::CreateFailure*); // noncopying version
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::Components::CreateFailure *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::Components::CreateFailure *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export void operator<<= (::CORBA::Any &, const Components::CreateFailure &); // copying version
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::CreateFailure*); // noncopying version
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::CreateFailure *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const Components::CreateFailure *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_exception\any_op_ch.cpp:38

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  

  CCM_STUB_Export void operator<<= (::CORBA::Any &, const ::Components::FinderFailure &); // copying version
  CCM_STUB_Export void operator<<= (::CORBA::Any &, ::Components::FinderFailure*); // noncopying version
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::Components::FinderFailure *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::Components::FinderFailure *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export void operator<<= (::CORBA::Any &, const Components::FinderFailure &); // copying version
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::FinderFailure*); // noncopying version
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::FinderFailure *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const Components::FinderFailure *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_exception\any_op_ch.cpp:38

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  

  CCM_STUB_Export void operator<<= (::CORBA::Any &, const ::Components::RemoveFailure &); // copying version
  CCM_STUB_Export void operator<<= (::CORBA::Any &, ::Components::RemoveFailure*); // noncopying version
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::Components::RemoveFailure *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::Components::RemoveFailure *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export void operator<<= (::CORBA::Any &, const Components::RemoveFailure &); // copying version
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::RemoveFailure*); // noncopying version
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::RemoveFailure *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const Components::RemoveFailure *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_exception\cdr_op_ch.cpp:37
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::CreateFailure &);
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::CreateFailure &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_exception\cdr_op_ch.cpp:37
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::FinderFailure &);
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::FinderFailure &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_exception\cdr_op_ch.cpp:37
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::RemoveFailure &);
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::RemoveFailure &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_codegen.cpp:1700
#include /**/ "ace/post.h"

#endif /* ifndef */

