// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:149

#ifndef _TAO_IDL_CCM_RECEPTACLEC_XGJ85N_H_
#define _TAO_IDL_CCM_RECEPTACLEC_XGJ85N_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "CCM_Stub_Export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/UserException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "ccm/CCM_BaseC.h"
#include "ccm/CCM_NavigationC.h"
#include "ccm/CCM_CookieC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 3 || TAO_BETA_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO CCM_STUB_Export

// TAO_IDL - Generated from
// be\be_visitor_root\root_ch.cpp:157
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:35

namespace Components
{

  // TAO_IDL - Generated from
  // be\be_visitor_exception\exception_ch.cpp:41

  class CCM_STUB_Export ExceededConnectionLimit : public ::CORBA::UserException
  {
  public:

    ExceededConnectionLimit (void);
    ExceededConnectionLimit (const ExceededConnectionLimit &);
    ~ExceededConnectionLimit (void);

    ExceededConnectionLimit &operator= (const ExceededConnectionLimit &);

    static void _tao_any_destructor (void *);

    static ExceededConnectionLimit *_downcast ( ::CORBA::Exception *);
    static const ExceededConnectionLimit *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_ExceededConnectionLimit;

  // TAO_IDL - Generated from
  // be\be_visitor_exception\exception_ch.cpp:41

  class CCM_STUB_Export CookieRequired : public ::CORBA::UserException
  {
  public:

    CookieRequired (void);
    CookieRequired (const CookieRequired &);
    ~CookieRequired (void);

    CookieRequired &operator= (const CookieRequired &);

    static void _tao_any_destructor (void *);

    static CookieRequired *_downcast ( ::CORBA::Exception *);
    static const CookieRequired *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_CookieRequired;

  // TAO_IDL - Generated from
  // be\be_interface.cpp:748

#if !defined (_COMPONENTS_RECEPTACLES__VAR_OUT_CH_)
#define _COMPONENTS_RECEPTACLES__VAR_OUT_CH_

  class Receptacles;
  typedef Receptacles *Receptacles_ptr;

  typedef
    TAO_Objref_Var_T<
        Receptacles
      >
    Receptacles_var;
  
  typedef
    TAO_Objref_Out_T<
        Receptacles
      >
    Receptacles_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be\be_visitor_interface\interface_ch.cpp:40

  class CCM_STUB_Export Receptacles
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<Receptacles>;

    // TAO_IDL - Generated from
    // be\be_type.cpp:304

    typedef Receptacles_ptr _ptr_type;
    typedef Receptacles_var _var_type;
    typedef Receptacles_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static Receptacles_ptr _duplicate (Receptacles_ptr obj);

    static void _tao_release (Receptacles_ptr obj);

    static Receptacles_ptr _narrow (::CORBA::Object_ptr obj);
    static Receptacles_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static Receptacles_ptr _nil (void);

    virtual ::Components::Cookie * connect (
      const char * name,
      ::CORBA::Object_ptr connection);

    virtual ::CORBA::Object_ptr disconnect (
      const char * name,
      ::Components::Cookie * ck);

    // TAO_IDL - Generated from
    // be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    Receptacles (void);

    // Concrete non-local interface only.
    Receptacles (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    Receptacles (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~Receptacles (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    Receptacles (const Receptacles &);

    void operator= (const Receptacles &);
  };

  // TAO_IDL - Generated from
  // be\be_visitor_typecode\typecode_decl.cpp:34

  extern CCM_STUB_Export ::CORBA::TypeCode_ptr const _tc_Receptacles;

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:64

} // module Components

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:145

#if !defined (_COMPONENTS_RECEPTACLES__ARG_TRAITS_)
#define _COMPONENTS_RECEPTACLES__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::Components::Receptacles>
    : public
        Object_Arg_Traits_T<
            ::Components::Receptacles_ptr,
            ::Components::Receptacles_var,
            ::Components::Receptacles_out,
            TAO::Objref_Traits<Components::Receptacles>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_COMPONENTS_RECEPTACLES__TRAITS_)
#define _COMPONENTS_RECEPTACLES__TRAITS_

  template<>
  struct CCM_STUB_Export Objref_Traits< ::Components::Receptacles>
  {
    static ::Components::Receptacles_ptr duplicate (
        ::Components::Receptacles_ptr p);
    static void release (
        ::Components::Receptacles_ptr p);
    static ::Components::Receptacles_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Components::Receptacles_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_exception\any_op_ch.cpp:38

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  

  CCM_STUB_Export void operator<<= (::CORBA::Any &, const ::Components::ExceededConnectionLimit &); // copying version
  CCM_STUB_Export void operator<<= (::CORBA::Any &, ::Components::ExceededConnectionLimit*); // noncopying version
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::Components::ExceededConnectionLimit *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::Components::ExceededConnectionLimit *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export void operator<<= (::CORBA::Any &, const Components::ExceededConnectionLimit &); // copying version
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::ExceededConnectionLimit*); // noncopying version
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::ExceededConnectionLimit *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const Components::ExceededConnectionLimit *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_exception\any_op_ch.cpp:38

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  

  CCM_STUB_Export void operator<<= (::CORBA::Any &, const ::Components::CookieRequired &); // copying version
  CCM_STUB_Export void operator<<= (::CORBA::Any &, ::Components::CookieRequired*); // noncopying version
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::Components::CookieRequired *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::Components::CookieRequired *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export void operator<<= (::CORBA::Any &, const Components::CookieRequired &); // copying version
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::CookieRequired*); // noncopying version
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::CookieRequired *&); // deprecated
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const Components::CookieRequired *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_interface\any_op_ch.cpp:41



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Components
{
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, Receptacles_ptr); // copying
  CCM_STUB_Export void operator<<= ( ::CORBA::Any &, Receptacles_ptr *); // non-copying
  CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Receptacles_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::Receptacles_ptr); // copying
CCM_STUB_Export void operator<<= (::CORBA::Any &, Components::Receptacles_ptr *); // non-copying
CCM_STUB_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Components::Receptacles_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be\be_visitor_exception\cdr_op_ch.cpp:37
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::ExceededConnectionLimit &);
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::ExceededConnectionLimit &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_exception\cdr_op_ch.cpp:37
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::CookieRequired &);
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::CookieRequired &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_interface\cdr_op_ch.cpp:41

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

CCM_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Components::Receptacles_ptr );
CCM_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Components::Receptacles_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_codegen.cpp:1700
#if defined (__ACE_INLINE__)
#include "CCM_ReceptacleC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

